/**
 * NAVI Trader - Sui Wallet Generator
 * Generates a new Sui wallet for the NAVI carry trade bot.
 */

import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { SuiClient } from "@mysten/sui/client";
import { writeFileSync, mkdirSync } from "fs";

const RPC = "https://fullnode.mainnet.sui.io:443";
const client = new SuiClient({ url: RPC });

function generateWallet() {
  const keypair = new Ed25519Keypair();
  const address = keypair.getPublicKey().toSuiAddress();

  return {
    address,
    created: new Date().toISOString(),
    chain: "sui",
    note: "Fund this wallet with small amount for testing. Generated by NAVI Trader bot.",
  };
}

async function checkBalance(address) {
  try {
    const coins = await client.getCoins({ owner: address });
    const total = coins.data.reduce((sum, c) => sum + parseFloat(c.balance), 0);
    return { coins: coins.data.length, total };
  } catch (e) {
    return { error: e.message };
  }
}

async function main() {
  const wallet = generateWallet();

  mkdirSync("config", { recursive: true });
  writeFileSync("config/wallet.json", JSON.stringify(wallet, null, 2));
  console.log("✅ Wallet saved to config/wallet.json");

  console.log("\n📛 WALLET ADDRESS:");
  console.log(wallet.address);
  console.log("");

  const balance = await checkBalance(wallet.address);
  if (balance.error) {
    console.log("⚠️  Balance check failed:", balance.error);
  } else {
    console.log(`💰 Balance: ${balance.total} SUI in ${balance.coins} coins`);
  }

  console.log("\n⚠️  IMPORTANT:");
  console.log("1. Send a SMALL amount of SUI to this address to test");
  console.log("2. Check balance at: https://suiscan.xyz/" + wallet.address);
  console.log("3. Once confirmed working, you can fund with larger amounts");
  console.log("4. NEVER share your wallet key — keep it secure!");

  return wallet;
}

main().catch(console.error);
